### PR TITLE
add use_task param to Pipeline node

### PR DESCRIPTION
**Pull request by morganOmind**

### CODE REVIEW

**Comment by mesca** [comment]
[DocInit](https://github.com/mesca/docinit) now works with setuptools 62. Does it fix your problem?

**Comment by morganOmind** [comment]
Hi, maybe it will, but for now I have to stay on my own fork because of the two previous commits [dbf24b1] and [fd27ea6] that enable timeflux breath calibration within a pyinstaller windows executable that we use in production.

**Comment by mesca** [comment]
The problem is that the `timeflux.helpers.background` module is calling the system default Python executable, which may be missing or missing dependencies.

You want to use the executable embedded within your PyInstaller distribution, and this can be fixed with some monkey-patching in a runtime hook:

```
from subprocess import Popen
import timeflux.helpers.background

def _start(self):
    self._process = Popen([sys.executable, "task", str(self._port)])
    self._send(
        {
            "instance": self.instance,
            "method": self.method,
            "args": self.args,
            "kwargs": self.kwargs
        }
    )
    return self

timeflux.helpers.background.Task.start = _start
``` 

Your entrypoint would look like this:

```
import sys, os
from multiprocessing import freeze_support
if __name__ == "__main__":
    freeze_support()
    if len(sys.argv) == 3 and sys.argv[1] == "task":
        from timeflux.helpers.background import Worker
        Worker(sys.argv[2]).execute()
    else:
        from timeflux.timeflux import main
        main()
```

This works well for me. I will try to release a complete build script, but if you have used PyInstaller before, you should probably be able to figure out how to use runtime hooks. Let me know if that solves your issue.

**Comment by morganOmind** [comment]
Thanks a lot, this workaround perfectly solved my issue. Thus I can abandon my fork repo and roll back to the official timeflux one :) You can close this PR, thanks again !

**Comment by mesca** [comment]
Great!

**Pull request closed without merging**
